import { Listing, User, AuditLog } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'admin@carrental.com',
    name: 'Admin User',
    role: 'admin',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    email: 'john@example.com',
    name: 'John Doe',
    role: 'user',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '3',
    email: 'jane@example.com',
    name: 'Jane Smith',
    role: 'user',
    createdAt: new Date('2024-01-20'),
  },
];

export const mockListings: Listing[] = [
  {
    id: '1',
    title: '2022 Toyota Camry - Clean & Reliable',
    description: 'Well-maintained Toyota Camry with low mileage. Perfect for daily commute or road trips.',
    price: 45,
    location: 'New York, NY',
    carModel: 'Toyota Camry',
    carYear: 2022,
    mileage: 25000,
    fuelType: 'gasoline',
    transmission: 'automatic',
    images: ['https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400'],
    status: 'pending',
    userId: '2',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    title: '2021 Honda Civic - Sport Edition',
    description: 'Sporty Honda Civic with excellent fuel efficiency and modern features.',
    price: 38,
    location: 'Los Angeles, CA',
    carModel: 'Honda Civic',
    carYear: 2021,
    mileage: 32000,
    fuelType: 'gasoline',
    transmission: 'automatic',
    images: ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=400'],
    status: 'approved',
    userId: '3',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: '3',
    title: '2023 Tesla Model 3 - Electric Luxury',
    description: 'Premium Tesla Model 3 with autopilot and long-range battery.',
    price: 85,
    location: 'San Francisco, CA',
    carModel: 'Tesla Model 3',
    carYear: 2023,
    mileage: 15000,
    fuelType: 'electric',
    transmission: 'automatic',
    images: ['https://images.unsplash.com/photo-1536700503339-1e4b06520771?w=400'],
    status: 'rejected',
    userId: '2',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-09'),
  },
  {
    id: '4',
    title: '2020 Ford Mustang - Classic Muscle',
    description: 'Powerful Ford Mustang with V8 engine and premium sound system.',
    price: 65,
    location: 'Miami, FL',
    carModel: 'Ford Mustang',
    carYear: 2020,
    mileage: 45000,
    fuelType: 'gasoline',
    transmission: 'manual',
    images: ['https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=400'],
    status: 'pending',
    userId: '3',
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: '5',
    title: '2021 BMW X5 - Luxury SUV',
    description: 'Luxurious BMW X5 with leather interior and advanced safety features.',
    price: 95,
    location: 'Chicago, IL',
    carModel: 'BMW X5',
    carYear: 2021,
    mileage: 28000,
    fuelType: 'gasoline',
    transmission: 'automatic',
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400'],
    status: 'approved',
    userId: '2',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-07'),
  },
  {
    id: '6',
    title: '2022 Hyundai Tucson - Family SUV',
    description: 'Spacious Hyundai Tucson perfect for family trips with excellent cargo space.',
    price: 42,
    location: 'Seattle, WA',
    carModel: 'Hyundai Tucson',
    carYear: 2022,
    mileage: 22000,
    fuelType: 'gasoline',
    transmission: 'automatic',
    images: ['https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400'],
    status: 'pending',
    userId: '3',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: '1',
    action: 'login',
    adminId: '1',
    adminName: 'Admin User',
    timestamp: new Date('2024-01-20T09:00:00'),
  },
  {
    id: '2',
    action: 'approve',
    adminId: '1',
    adminName: 'Admin User',
    listingId: '2',
    listingTitle: '2021 Honda Civic - Sport Edition',
    timestamp: new Date('2024-01-12T14:30:00'),
  },
  {
    id: '3',
    action: 'reject',
    adminId: '1',
    adminName: 'Admin User',
    listingId: '3',
    listingTitle: '2023 Tesla Model 3 - Electric Luxury',
    details: 'Incomplete documentation',
    timestamp: new Date('2024-01-09T11:15:00'),
  },
  {
    id: '4',
    action: 'approve',
    adminId: '1',
    adminName: 'Admin User',
    listingId: '5',
    listingTitle: '2021 BMW X5 - Luxury SUV',
    timestamp: new Date('2024-01-07T16:45:00'),
  },
  {
    id: '5',
    action: 'edit',
    adminId: '1',
    adminName: 'Admin User',
    listingId: '2',
    listingTitle: '2021 Honda Civic - Sport Edition',
    details: 'Updated price from $40 to $38',
    timestamp: new Date('2024-01-12T15:20:00'),
  },
]; 